### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by pog87** [ohbm/hackathon2019#11]
"openness is the norm and siloes the exception"

it might be some mispelling, unless you're really referring to siloes :-P

![alt](http://willvideoforfood.com/wp-content/uploads/2009/08/Snapz-Pro-XScreenSnapz0051.jpg)

**Comment by KirstieJane** [comment]
It's the same word! https://en.wiktionary.org/wiki/silo

I found a few different versions of the plural form: silos or siloes. Silos I think is the recommended one, [wiktionary](https://en.wiktionary.org/wiki/siloes) says siloes is a "dated form".

**Comment by pog87** [comment]
I'm learning something new! thanks
