### ISSUE TITLE
Adding brainhack short courses to the list of resources?

### ISSUE THREAD

**Issue by cmaumet** [ohbm/hackathon2019#6]
Hi! Thanks for putting together this great [list of resources](https://github.com/ohbm/hackathon2019/blob/master/Tutorial_Resources.md). 

Have you already considered adding links to videos from previous Brainhacks as listed at: http://www.brainhack.org/lectures.html?

**Comment by katjaq** [comment]
Hello! This is a fantastic idea! Thank you @cmaumet for pointing this out. We will link them all. Maybe I should quickly scroll through and add for each one what topics they cover...?
If you would like to add links, please feel also free to make a PR :)

Thank you very much again for pointing us to this resource!
Best 
katja

**Comment by katjaq** [comment]
Hi again! 
I am reaching out to invite the community to create this list. I broke down this link into 4 separate issues and hope this is how people feel they can handle the amount of work and jump in to help us :) and maybe they will even know other resources they want to link :)
So I am closing this issue now, and will refer to the new 4 issues :) 

Many thanks again @cmaumet :)
best, katja

**Comment by cmaumet** [comment]
This is great! +1 
Thanks @katjaq
